#!/bin/sh

#This script enables debugging between the real smartphone and the smartwatch emulator
echo "Enabling debugging between real smartphone and smartwatch emulator"

cd Library/Android/sdk/platform-tools
./adb -d forward tcp:5601 tcp:5601
./adb connect 127.0.0.1:5601

echo "Enabling done"